version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: "@types*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: 'npm'
    directory: 'apps/makeosc'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: 'apps/readosc'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: 'apps/sendosc'
    schedule:
      interval: 'weekly'
